-------------------------------------------------------------------------------
Test set: com.taoyuanx.test.ClerkTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.461 s <<< FAILURE! - in com.taoyuanx.test.ClerkTest
add(com.taoyuanx.test.ClerkTest)  Time elapsed: 0.167 s  <<< ERROR!
org.springframework.ldap.NameAlreadyBoundException: [LDAP: error code 68 - Entry Already Exists]; nested exception is javax.naming.NameAlreadyBoundException: [LDAP: error code 68 - Entry Already Exists]; remaining name 'cn=gino,ou=taobao'
	at com.taoyuanx.test.ClerkTest.add(ClerkTest.java:30)
Caused by: javax.naming.NameAlreadyBoundException: [LDAP: error code 68 - Entry Already Exists]
	at com.taoyuanx.test.ClerkTest.add(ClerkTest.java:30)

